django_pro/basic_app/urls.py
from basic_app import views
from django.urls import path

app_name = 'basic_app'

urlpatterns = [
    path('register/',views.register,name='register'),
    path('other/',views.other,name='other'),
    path('login',views.user_login,name='user_login')
]

django_pro/django_pro/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path('',views.index,name='index'),
    path('basic_app/',include('basic_app.urls')),
    path('admin/', admin.site.urls),
    path('logout/',views.user_logout,name='logout')
]

django_pro/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    site = models.URLField(blank=True)

    profile_pic = models.ImageField(upload_to='basic_app/media',blank=True)
     
    def __str__(self):
        return self.user.username

django_pro/basic_app/forms.py
from django import forms
from .models import UserProfileInfo
from django.contrib.auth.models import User

class UserFrom(forms.ModelForm):
    """docstring for UserProfileInfoFrom."""

    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    """docstring for UserProfileInfoForm."""

    class Meta():
        model = UserProfileInfo
        fields = ('site','profile_pic')

django_pro/basic_app/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect

# Extra imports
from django.contrib.auth import authenticate, login, logout
from .forms import UserFrom, UserProfileInfoForm
from django.urls import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.

def index(request):
    return render(request,'basic_app/index.html')

@login_required
def other(request):
    return render(request,'basic_app/other.html')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

    
def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserFrom(data=request.POST)
        user_profile = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and user_profile.is_valid():

            user = user_form.save()

            user.set_password(user.password)

            user.save()

            profile = user_profile.save(commit=False)

            profile.user = user

            if 'profile_pic' in request.FILES:
                print('found it')
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True

        else:
            print(user_form.errors,user_profile.errors)

    else:
        user_form = UserFrom()
        user_profile = UserProfileInfoForm()

    return render(request,'basic_app/registration.html',
                         {'user_form':user_form,
                          'user_profile':user_profile,
                          'registered':registered})



def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        # authenticate the user
        user = authenticate(username=username,password=password)

        # if we have a user
        if user:
        # check if user is active
            if user.is_active:
                login(request,user)

                # send user back to homepage
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("user is not active")

        else:
            return HttpResponse("not a user")


    else:
        return render(request,'basic_app/login.html')

django_pro/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <title>Django Test</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="navbar-nav">
        <a class="navbar-brand" href="{% url 'index'%}">Django</a>
        <a class="nav-item nav-link" href="{% url 'admin:index'%}">Admin</a>
        <a class="nav-item nav-link" href="{% url 'basic_app:register' %}">Resgister</a>
        {% if user.is_authenticated %}
        <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
        <a class="nav-item nav-link" href="{% url 'basic_app:other'%}">Other</a>
        {% else %}
        <a class="nav-item nav-link" href="{% url 'basic_app:user_login' %}">Login</a>
        {% endif %}
      </div>
    </nav>

    <div class="container">
      <div class="jumbotron">
        {% block body_block %}
        {% endblock%}
      </div>
    </div>
  </body>
</html>

django_pro/templates/basic_app/index.html
<!DOCTYPE html>
{% extends 'basic_app/base.html'%}
{% block body_block %}

  <h1>WELCOME TO DJANGO TEST APP</h1>

{% endblock%}

django_pro/templates/basic_app/login.html
{% extends 'basic_app/base.html' %}
{% block body_block %}

  <h2>Login Here</h2>

  <form method="post" action="{% url 'basic_app:user_login' %}" >
    {% csrf_token %}
    <label for="username">Username:</label>
    <input type="text" name="username" placeholder="username">
    <p></p>
    <label for="password">Password:</label>
    <input type="password" name="password" placeholder="password">
    <input class="btn btn-primary btn-sm" type="submit" value="Login">
  </form>

{% endblock %}

django_pro/templates/basic_app/other.html
<!DOCTYPE html>
{% extends 'basic_app/base.html'%}
{% block body_block %}

  <h1>WELCOME TO OTHER</h1>
{% endblock %}

django_pro/templates/basic_app/registration.html
{% extends 'basic_app/base.html'%}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% block body_block %}

  {% if registered %}
    <h1>Thanks for registering mofo </h1>
  {% else %}
  <h1>Register Here</h1>
  <h2>Please fill out the form:</h2>

  <form enctype="multipart/form-data" method="POST">
    {% csrf_token %}
    {{ user_form|crispy }}
    {{ user_profile|crispy }}
    <input class="btn btn-primary" type="submit" value="Register">
  </form>
  {% endif %}
{% endblock %}